package com.share.jack.greendao.generator;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.share.jack.greendao.bean.ArticleInfo;
import com.share.jack.greendao.bean.UserInfo;

import com.share.jack.greendao.generator.ArticleInfoDao;
import com.share.jack.greendao.generator.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final ArticleInfoDao articleInfoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleInfoDaoConfig = daoConfigMap.get(ArticleInfoDao.class).clone();
        articleInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        articleInfoDao = new ArticleInfoDao(articleInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(ArticleInfo.class, articleInfoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        articleInfoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public ArticleInfoDao getArticleInfoDao() {
        return articleInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
